#!/bin/bash
# 每日英语学习 - 每天学习英语表达

echo "=== $(date) English Learning ==="

PHRASES=(
  "Ship it - 发布/推出产品"
  "Ship fast - 快速发布"
  "Dogfood - 使用自己的产品"
  "Ship your work - 交付工作"
  "Ship or die - 必须交付"
  "Get shipped - 被发布"
  "LGTM - Looks Good To Me"
  "TL;DR - Too Long; Didn't Read"
  "IYKYK - If You Know You Know"
  "WIP - Work In Progress"
)

PHRASE=${PHRASES[$((RANDOM % ${#PHRASES[@]}))]}
echo "Today's phrase: $PHRASE"

# 创建学习笔记
NOTE_FILE="/home/zous/clawd/.learning/english/$(date +%Y-%m-%d).md"
mkdir -p "$(dirname "$NOTE_FILE")"

cat > "$NOTE_FILE" << EOF
# English Learning - $(date '+%Y-%m-%d')

## Today's Phrase
$PHRASE

## Context

## Example

## Related

---
Generated by English Learning System
EOF

echo "Note created: $NOTE_FILE"
echo "=== Learning Complete ==="
