#!/bin/bash
# 每日技术学习 - 每天学习一个新的技术概念

echo "=== $(date) Daily Tech Learning ==="

# 随机选择一个技术主题学习
TOPICS=(
  "LangGraph State Machines"
  "Memory Systems: ACT-R vs Human-LLM"
  "Vector Databases: FAISS vs Chroma vs Pinecone"
  "RAG Optimization: HyDE, Rerankers"
  "Agent Frameworks: LangGraph vs CrewAI vs AutoGen"
  "Prompt Engineering: Chain-of-Thought vs Tree-of-Thought"
  "MCP Protocol Deep Dive"
  "Function Calling Best Practices"
  "Embedding Models Comparison"
  "Context Window Optimization"
)

TOPIC=${TOPICS[$((RANDOM % ${#TOPICS[@]}))]}
echo "Today's Topic: $TOPIC"

# 创建学习笔记
NOTE_FILE="/home/zous/clawd/memory/tech-learning/$(date +%Y-%m-%d)-learning.md"
mkdir -p "$(dirname "$NOTE_FILE")"

cat > "$NOTE_FILE" << EOF
# $(date +%Y-%m-%d) Tech Learning: $TOPIC

## 学习内容
$TOPIC

## 关键概念

## 代码示例

## 参考资源

## 下一步行动

---
Generated by Daily Tech Learning System
EOF

echo "Learning note created: $NOTE_FILE"
echo "=== Learning Complete ==="
