#!/bin/bash
# 每日灵感收集 - 每天 2 次收集创意和灵感

echo "=== $(date) Inspiration Collection ==="

INSPIRATION_FILE="/home/zous/clawd/.inspiration/$(date +%Y-%m-%d).md"
mkdir -p "$(dirname "$INSPIRATION_FILE")"

# 收集当天的灵感
cat > "$INSPIRATION_FILE" << EOF
# Inspiration - $(date '+%Y-%m-%d')

## 代码灵感

## 项目想法

## 学习方向

## 待探索技术

## 今日金句

---
Generated by Inspiration Collection System
EOF

echo "Inspiration file created: $INSPIRATION_FILE"

# 检查是否有新的 TODO 或想法
TODOS=$(grep -r "TODO\|IDEA\|MAYBE\|explore" /home/zous/clawd --include="*.md" --include="*.py" 2>/dev/null | wc -l)
echo "Ideas/TODOs found in codebase: $TODOS"

# 记录
echo "$(date '+%Y-%m-%d %H:%M') | Ideas file created | TODOs in codebase: $TODOS" >> /home/zous/clawd/.logs/inspiration-collection.log

echo "=== Collection Complete ==="
