#!/bin/bash
# 每日心态检查 - 每天反思工作状态

echo "=== $(date) Mindset Check ==="

cat > "/home/zous/clawd/.mindset/$(date +%Y-%m-%d).md << EOF
# Mindset Check - $(date '+%Y-%m-%d')

## 今日状态

### 能量水平
- [ ] 低
- [ ] 中
- [ ] 高

### 工作效率
- [ ] 低
- [ ] 中
- [ ] 高

### 学习进度
- [ ] 低
- [ ] 中
- [ ] 高

## 今日亮点

## 今日挑战

## 明日目标

## 一句话总结

---
Generated by Mindset Check System
EOF

echo "Mindset file created"

# 检查近期的情绪趋势
RECENT_FILES=$(ls /home/zous/clawd/.mindset/*.md 2>/dev/null | wc -l)
echo "Total mindset records: $RECENT_FILES"

# 记录
echo "$(date '+%Y-%m-%d %H:%M') | Mindset check recorded" >> /home/zous/clawd/.logs/mindset-check.log

echo "=== Check Complete ==="
